import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import 'cross-fetch/polyfill';
// import eventsource from 'eventsource';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontHeading = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});



const fontBody = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontHeading.variable}
         ${fontBody.variable} bg-lightGray`}
      >
        <Header>
          <Header.Logo />
          {Header.Cta && (
            <Header.Cta>
              {Header.Cta?.PostABountyCta && <Header.Cta.PostABountyCta />}
              {Header.Cta?.JoinAsAHunterCta && <Header.Cta.JoinAsAHunterCta />}
            </Header.Cta>
          )}
        </Header>
        {children}
      </body>
    </html>
  );
}
